name: Test
on: [pull_request]
jobs:
  build:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: nuxt/actions-yarn@node-10
        with:
          cmd: install # runs `yarn install`
      - uses: nuxt/actions-yarn@node-10
        with:
          cmd: test # runs `yarn test`
